fix | Implement de_ignored_any to consume unknown map fields
trussed-dev/cbor-smol pull request #5
Opened 2023-07-13 03:55 UTC by frunobulax-the-poodle

# Issue

When deserializing a struct with additional fields (e.g. [transports](https://w3c.github.io/webauthn/#dictionary-credential-descriptor) or extensions, the key is consumed, but the value is skipped entirely and not consumed.

When deserialization continues, there is leftover unexpected data in the input, leading to errors (usually bad major)

# Fix

Implement `deserialize_ignored_any` on for `Deserializer`, so the values are fully consumed.

This does kind of go against not supporting `deserialize_any`, but I don't think there's a way around it.

2023-11-16 08:50 UTC, sosthene-nitrokey requested changes
Thank you for the pull request.

However I believe that `ignored_any` should completely ignore the value and end on a `visit_unit`. For example that is what `serde_json` does: https://docs.rs/serde_json/latest/src/serde_json/de.rs.html#1897-1903

2023-11-16 08:50 UTC, sosthene-nitrokey commented on src/de.rs
> +            1 => self.deserialize_i32(visitor),
This means that a value that does not fit in a `i32` or a `u32` de-serialization will fail.
I believe this should not actually de-serialize the value but just discard it.

2023-11-16 08:50 UTC, sosthene-nitrokey commented on src/de.rs
> +    }
Here if you replace the `u8` with `u64` and `22` with `0xFFFFFFFFF` this will lead to `DeserializeBadU32`.

2023-11-18 14:42 UTC, frunobulax-the-poodle commented
> Thank you for the pull request.
> 
> However I believe that `ignored_any` should completely ignore the value and end on a `visit_unit`. For example that is what `serde_json` does: https://docs.rs/serde_json/latest/src/serde_json/de.rs.html#1897-1903

Seems you're right. This was pretty far outside mywheelhouse so I expected to screw something up :)
As you've already got an [improved PR](https://github.com/nickray/cbor-smol/pull/6) out and are in a better position to maybe actually get it merged I'd be happy to just close this one.

2024-09-13 14:47 UTC, sosthene-nitrokey commented
I will close this PR in favour of https://github.com/trussed-dev/cbor-smol/pull/6

Now that this has been moved to `trussed-dev` we (Nitrokey) will be able to merge and release the other PRs.

Thank you.

2024-09-13 14:47 UTC, closed without merging